import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Header } from '@/components/header/Header';
import { cn } from '@/shared/lib/utils';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, 'min-h-screen')}>
        <Header />
        <div className='min-h-[calc(100vh-var(--header-height))]'>{children}</div>
      </body>
    </html>
  );
}
