import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Header } from "@/components/header/Header";
import { cn } from "@/shared/lib/utils";

import "./globals.css";
import { AuthProvider } from "@/provider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn(inter.className, "h-screen")}>
        {/* <Header /> */}
        <div className='h-full w-full'>
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
